# Generated by Django 4.2.16 on 2024-11-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenConMetadatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes/', verbose_name='Imagen')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('autor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Autor')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='metadatos')),
            ],
            options={
                'verbose_name': 'Imagen con metadatos',
                'verbose_name_plural': 'Imágenes con metadatos',
            },
        ),
    ]
