# Generated by Django 4.2.16 on 2024-11-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes/', verbose_name='Imagen')),
                ('image_path', models.CharField(max_length=255)),
                ('format', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('mode', models.CharField(max_length=50)),
                ('exif_metadata', models.JSONField(blank=True, null=True)),
                ('gps_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagen con metadatos',
                'verbose_name_plural': 'Imágenes con metadatos',
            },
        ),
        migrations.DeleteModel(
            name='ImagenConMetadatos',
        ),
    ]
