# Generated by Django 4.2.16 on 2024-11-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0002_metadatos_delete_imagenconmetadatos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadatos',
            options={},
        ),
        migrations.AlterField(
            model_name='metadatos',
            name='format',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='metadatos',
            name='image_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='metadatos',
            name='mode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='metadatos',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
