# Generated by Django 4.2.16 on 2024-11-16 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
