# Generated by Django 4.2.16 on 2024-11-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del post', max_length=200)),
                ('content_markdown', models.TextField(help_text='Contenido en formato Markdown')),
                ('content_html', models.TextField(editable=False, help_text='Contenido renderizado en HTML')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última fecha de actualización')),
            ],
        ),
    ]
